Celery, нити и обновление прогресса
===================================
:date: 2014-01-26 23:49:51
:modified: 2014-01-26 23:50:23
:tags: Celery, нить, обработка, обновление, дочерний, прогресс
:category: text
:author: IMDagger
:yaru-link: http://imdagger.ya.ru/replies.xml?item_no=1922

Похоже, что celery.current\_task.update\_state не дружит с вызовом
из области другой нити. Если создать нити и обернуть вызов обновления
состояния в Lock, чтобы не было параллельного обращения, то всё равно
рабочий процесс от Celery останавливается и не больше отзывается и чтобы
сделать restart нужно сначала его сбить. Не изучал вопрос почему, но
скорее всего из-за того, что я использую Celery “в связке для ленивых”,
т.е. с MySQL; а вот уже его драйверу возможно и не нравится, когда я
дёргаю его из одной нити, а создавал в другой. Произвёл вызов обновления
состояния в основном потоке в цикле по ожиданию события (плюс по
истечению интервала времени) и всё заработало как хотелось, а прогресс
обновления стал передавать по событию от дочерних нитей.
